<a href="https://colab.research.google.com/github/chebbin/datasci_2_manipulation/blob/main/hha507hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import re
import numpy as np

# Data Manipulation in Python: Pandas, Polars, Dask and Modin

In [50]:
df = pd.read_csv ('/content/healthcare_data_cleaning (1).csv')
df.tail(10)

,Patient Age,Gender,City of Residence,State of Residence,Has Insurance,Visited Last Month,Payment Method,Preferred Doctor,Disease Diagnosed,Medication Prescribed,Type of Appointment,Average Heart Rate,Average BP,Height (in cm),Weight (in kg),Payment Due ($),Last Visit (days ago),Visit Duration (mins),Number of Tests,Prescription Cost ($)
104990,52,Female,Lake April,Nebraska,No,No,Insurance,Dr. Johnson,Flu,missing,General,72,116,166,73,80.21182948231642,182,35,4,137.19185373324555
104991,70,Female,Johnsontown,Indiana,Yes,No,Card,Dr. Smith,Cold,Med_D,Emergency,77,missing,182,missing,188.60184820298264,168,107,1,21.006745688613698
104992,44,Female,Port Tracistad,Alaska,Yes,No,Insurance,Dr. Brown,Cold,Med_A,Follow-Up,76,93,178,66,462.56567087397013,189,55,3,59.74631825267156
104993,42,Female,West Annaport,Florida,Yes,No,Cash,Dr. Johnson,Covid-19,Med_D,Specialist,80,129,171,78,131.35632576282202,185,22,6,104.43016736588544
104994,53,Female,Michelleburgh,South Dakota,No,No,Card,Dr. Williams,Flu,Med_B,Emergency,68,109,172,75,488.0316041186948,167,25,5,69.54228578689846
104995,74,Other,West Anthony,Oklahoma,Yes,No,Card,Dr. Williams,Covid-19,Med_E,Specialist,65,112,169,61,309.16444606680665,183,10,3,63.20478776719894
104996,37,Male,Mckeetown,Utah,Yes,No,Cash,Dr. Jones,Covid-19,Med_C,General,missing,111,165,67,missing,191,47,2,113.86764025370326
104997,51,Female,Lake Lisachester,Nebraska,Yes,Yes,Insurance,Dr. Williams,Allergy,Med_D,Follow-Up,89,118,179,71,320.8304180033907,172,39,3,35.622420232475356
104998,missing,Female,Heidiborough,missing,Yes,No,Cash,Dr. Smith,Covid-19,Med_A,Follow-Up,74,123,167,75,5.341231420036174,180,79,missing,124.4083409893742
104999,45,Female,South Jeffrey,Massachusetts,No,Yes,Cash,Dr. Brown,Allergy,Med_D,General,77,140,167,62,454.94983945860804,167,81,missing,87.91060149353706

In [10]:
## Check for missing column values
print(df.isnull().sum())

Patient Age              0
Gender                   0
City of Residence        0
State of Residence       0
Has Insurance            0
Visited Last Month       0
Payment Method           0
Preferred Doctor         0
Disease Diagnosed        0
Medication Prescribed    0
Type of Appointment      0
Average Heart Rate       0
Average BP               0
Height (in cm)           0
Weight (in kg)           0
Payment Due ($)          0
Last Visit (days ago)    0
Visit Duration (mins)    0
Number of Tests          0
Prescription Cost ($)    0
dtype: int64

In [11]:
## Drop rows with any missing values
print(df.dropna(inplace=True))

None

In [12]:
## Check for any duplicate rows and columns
print(df.drop_duplicates(inplace=True))

None

In [25]:
## Remove leading and trailing white space from all columns
def clean_column_names(df):
  def clean_name(name):
      cleaned_name = re.sub(r'[^a-zA-Z0-9]', '', name)
      return cleaned_name.lower()
  df.columns = [clean_name(col) for col in df.columns]
  return df

df2 = clean_column_names(df)

print(df2.head(10))

  patientage   gender    cityofresidence stateofresidence hasinsurance  \
0         45    Other         West Brian         Kentucky          Yes
1         25   Female   East Jocelynfurt         Colorado           No
2         51    Other  South Lindseyland             Ohio          Yes
3         18   Female         Taylorfort     Pennsylvania          Yes
4         48   Female          Birdmouth          Montana           No
5         62  missing       North Donald         Oklahoma           No
6         52     Male      Lake Jennifer          missing           No
7         52     Male       Vanessaburgh      Connecticut          Yes
8         20   Female   West Briannabury          Montana           No
9         21     Male       East Joeview            Idaho          Yes

  visitedlastmonth paymentmethod preferreddoctor diseasediagnosed  \
0              Yes     Insurance    Dr. Williams              Flu
1              Yes          Card     Dr. Johnson              Flu
2               No          Cash    Dr. Williams         Covid-19
3          missing          Cash    Dr. Williams              Flu
4               No     Insurance       Dr. Brown             None
5              Yes          Card       Dr. Jones         Covid-19
6               No          Cash         missing         Covid-19
7              Yes     Insurance    Dr. Williams              Flu
8              Yes          Card       Dr. Jones              Flu
9               No     Insurance    Dr. Williams          Allergy

  medicationprescribed typeofappointment averageheartrate averagebp  \
0                Med_E           General               66       111
1                Med_B        Specialist               59   missing
2                Med_D           General               79       119
3                Med_A           General               99       115
4                Med_C        Specialist               93        89
5                Med_B           General               89       118
6                Med_A         Emergency               76       114
7                Med_E           General               99       129
8                Med_C        Specialist               67       108
9              missing           General               74       112

  heightincm weightinkg          paymentdue lastvisitdaysago  \
0        183         70   65.45721578126224              193
1        174         58  430.68365678679174              195
2        161         56   315.0709305262176          missing
3        171         52   320.2998987723972              175
4        186         87   264.2147372473319              188
5        185         88  207.63803813727571              185
6        155         70             missing              187
7        170         47  387.08504353508863              179
8        173         86   172.5483427968999              174
9    missing         70  21.564702145057733              192

  visitdurationmins numberoftests    prescriptioncost
0                92             5   15.71751735532889
1           missing             4   80.78647284463952
2                37             2    64.3921393009105
3               108             2   8.872859215315316
4               113             3   77.48311304645532
5               101             2  38.565586978808525
6                41             4    85.4804962270874
7               108             2   76.96592632951703
8                91             2  142.31710767890775
9               116             2   98.41627353050941

# Changes to column names

The column names have now been changed to all lowercase letters, no white space and no special characters. The new names are listed below.

In [14]:
list(df2)

['patientage',
 'gender',
 'cityofresidence',
 'stateofresidence',
 'hasinsurance',
 'visitedlastmonth',
 'paymentmethod',
 'preferreddoctor',
 'diseasediagnosed',
 'medicationprescribed',
 'typeofappointment',
 'averageheartrate',
 'averagebp',
 'heightincm',
 'weightinkg',
 'paymentdue',
 'lastvisitdaysago',
 'visitdurationmins',
 'numberoftests',
 'prescriptioncost']

# Goup by Gender

In [38]:
gp = df.groupby('gender').describe()
gp

        patientage                       cityofresidence                  \
             count unique      top  freq           count unique      top
gender
Female       31674     83  missing  1559           31674  17873  missing
Male         31728     84  missing  1653           31728  17870  missing
Other        31598     83  missing  1548           31598  17806  missing
missing       5000     78  missing   240            5000   4112  missing

              stateofresidence         ... visitdurationmins        \
         freq            count unique  ...               top  freq
gender                                 ...
Female   1562            31674     51  ...           missing  1513
Male     1614            31728     51  ...           missing  1675
Other    1584            31598     51  ...           missing  1559
missing   240             5000     51  ...           missing   253

        numberoftests                  prescriptioncost
                count unique top  freq            count unique      top  freq
gender
Female          31674     12   4  7620            31674  30098  missing  1577
Male            31728     12   4  7530            31728  30102  missing  1627
Other           31598     12   4  7459            31598  30076  missing  1523
missing          5000     11   4  1186             5000   4728  missing   273

[4 rows x 76 columns]

# Change String values to Integers

This was unsuccessful

In [46]:
df['averageheartrate'] = df['averageheartrate'].astype(int)

ValueError: ignored

# Group by gender and average heart rate

This was also unsuccessful

In [42]:
gp2 = df.groupby('gender').agg({
    'averageheartrate': 'mean'
    })
gp2

TypeError: ignored

# POLARS exercise

In [ ]:
import polars as pl
import time

In [ ]:
df3 = pl.read_csv('/content/healthcare_data_cleaning (1).csv')
df3.head(10)

shape: (10, 20)
┌───────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Patient   ┆ Gender ┆ City of    ┆ State of   ┆ … ┆ Last Visit ┆ Visit      ┆ Number of  ┆ Prescripti │
│ Age       ┆ ---    ┆ Residence  ┆ Residence  ┆   ┆ (days ago) ┆ Duration   ┆ Tests      ┆ on Cost    │
│ ---       ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ (mins)     ┆ ---        ┆ ($)        │
│ str       ┆        ┆ str        ┆ str        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│           ┆        ┆            ┆            ┆   ┆            ┆ str        ┆            ┆ str        │
╞═══════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 45        ┆ Other  ┆ West Brian ┆ Kentucky   ┆ … ┆ 193        ┆ 92         ┆ 5          ┆ 15.7175173 │
│           ┆        ┆            ┆            ┆   ┆            ┆            ┆            ┆ 5532889    │
│ 25        ┆ Female ┆ East Jocel ┆ Colorado   ┆ … ┆ 195        ┆ missing    ┆ 4          ┆ 80.7864728 │
│           ┆        ┆ ynfurt     ┆            ┆   ┆            ┆            ┆            ┆ 4463952    │
│ 51        ┆ Other  ┆ South Lind ┆ Ohio       ┆ … ┆ missing    ┆ 37         ┆ 2          ┆ 64.3921393 │
│           ┆        ┆ seyland    ┆            ┆   ┆            ┆            ┆            ┆ 009105     │
│ 18        ┆ Female ┆ Taylorfort ┆ Pennsylvan ┆ … ┆ 175        ┆ 108        ┆ 2          ┆ 8.87285921 │
│           ┆        ┆            ┆ ia         ┆   ┆            ┆            ┆            ┆ 5315316    │
│ …         ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 52        ┆ Male   ┆ Lake       ┆ missing    ┆ … ┆ 187        ┆ 41         ┆ 4          ┆ 85.4804962 │
│           ┆        ┆ Jennifer   ┆            ┆   ┆            ┆            ┆            ┆ 270874     │
│ 52        ┆ Male   ┆ Vanessabur ┆ Connecticu ┆ … ┆ 179        ┆ 108        ┆ 2          ┆ 76.9659263 │
│           ┆        ┆ gh         ┆ t          ┆   ┆            ┆            ┆            ┆ 2951703    │
│ 20        ┆ Female ┆ West Brian ┆ Montana    ┆ … ┆ 174        ┆ 91         ┆ 2          ┆ 142.317107 │
│           ┆        ┆ nabury     ┆            ┆   ┆            ┆            ┆            ┆ 67890775   │
│ 21        ┆ Male   ┆ East       ┆ Idaho      ┆ … ┆ 192        ┆ 116        ┆ 2          ┆ 98.4162735 │
│           ┆        ┆ Joeview    ┆            ┆   ┆            ┆            ┆            ┆ 3050941    │
└───────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘